ecmaFeatures:
  modules: true
  jsx: true
parser: babel-eslint
rules:
  space-before-function-paren:
    - 2
    -
      anonymous: always
      named: never
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 1
    - always
  comma-dangle:
    - 0
  no-console:
    - 1
env:
  es6: true
  browser: true
  node: true
#extends: 'eslint:recommended'
