ecmaFeatures:
  modules: true
  jsx: true

parser: babel-eslint

plugins:
  - react

rules:
  space-before-function-paren:
    - 2
    - anonymous: always
      named: never
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 1
    - always
  comma-dangle:
    - 0
  no-console:
    - 1
  no-unused-vars:
    - 1
    - argsIgnorePattern: ^_

  react/jsx-uses-react: 1
  #react/jsx-uses-vars: 1

env:
  es6: true
  browser: true
  node: true
  jasmine: true

# https://github.com/eslint/eslint/blob/master/conf/eslint.json
extends: 'eslint:recommended'
